FROM amazoncorretto:8

WORKDIR /app

COPY . .

# Naprawa CRLF -> LF
RUN sed -i 's/\r$//' mvnw

RUN ./mvnw package

# CMD ["java", "-jar", "target/spring-example-project-1.1.3.jar"]
CMD ["sh", "-c", "java -jar target/*.jar"]